#———————————————————————————————————————————————————————————————————————
# gz_msgs_extras_hh
# 
cc_library(
  name = "gz_msgs_extras_hdrs",
  hdrs = ["gz/msgs/extras.hh"],
  includes = ["."],
  deps = [
    "@gz-msgs9//:time_cc_proto",
    "@gz-msgs9//:topic_info_cc_proto",
    "@gz-msgs9//:wrench_cc_proto",
  ],
  visibility = ["//visibility:public"],
)
