#———————————————————————————————————————————————————————————————————————
# ignition_msgs_extras_hh
# 
cc_library(
  name = "ignition_msgs_extras_hdrs",
  hdrs = ["ignition/msgs/extras.hh"],
  includes = ["."],
  deps = [
    "@ign-msgs9//:time_cc_proto",
    "@ign-msgs9//:topic_info_cc_proto",
    "@ign-msgs9//:wrench_cc_proto",
  ],
  visibility = ["//visibility:public"],
)
